export enum FilterActionTypes {
  GET_TAGS = "GET_TAGS",
  SET_TAGS = "SET_TAGS",

  GET_BRANDS = "GET_BRANDS",
  SET_BRANDS = "SET_BRANDS",

  SET_FILTER_BY_TAG = "SET_FILTER_BY_TAG",
  SET_FILTER_BY_BRAND = "SET_FILTER_BY_BRAND"
}