export const ADD_FILTER_BY_TAG = "ADD_FILTER_BY_TAG";
export const REMOVE_FILTER_BY_TAG = "REMOVE_FILTER_BY_TAG";

export const ADD_FILTER_BY_BRAND = "ADD_FILTER_BY_BRAND";
export const REMOVE_FILTER_BY_BRAND = "REMOVE_FILTER_BY_BRAND";