// Copyright (c) 2022-present Onur Pamuk. All Rights Reserved.

export const ADD_FILTER_BY_TAG = "ADD_FILTER_BY_TAG";
export const REMOVE_FILTER_BY_TAG = "REMOVE_FILTER_BY_TAG";

export const ADD_FILTER_BY_BRAND = "ADD_FILTER_BY_BRAND";
export const REMOVE_FILTER_BY_BRAND = "REMOVE_FILTER_BY_BRAND";
export const SET_ORDER_BY = "SET_ORDER_BY";

export const ADD_FILTER_BY_ITEM_TYPE = "ADD_FILTER_BY_ITEM_TYPE";
export const REMOVE_FILTER_BY_ITEM_TYPE = "REMOVE_FILTER_BY_ITEM_TYPE";